### ISSUE TITLE
 About 'kinetics_i3dresnet101__rgb_model_best.pth.tar'

### ISSUE THREAD

**Issue by liudaizong** [feiyunzhang/i3d-nonlocal-pytorch#1]
Hi! Can u provide the 'kinetics_i3dresnet101__rgb_model_best.pth.tar'?

**Comment by feiyunzhang** [comment]
i just run "run_i3d_baseline_400k_32f"  in xiaolong's repo. maybe 0.5% lower than the caffe2 model result.

**Comment by feiyunzhang** [comment]
I just run 45 epoch about 62% MAP, it needs to train about 120 epoch to get to the paper's reuslt. Maybe it have some problems about nonlocal moudel. You can download the model here: http://pbzrvm8c9.bkt.clouddn.com/model/kinetics_i3dresnet101__rgb_model_best.pth.tar
