### ISSUE TITLE
finetune in i3d-non-local

### ISSUE THREAD

**Issue by variousxin** [feiyunzhang/i3d-nonlocal-pytorch#10]
hello, thanks for building this project! I want to finetune my own dataset using this method. Do you have the pretrained weights trained in Kinetics or other large-scale datasets？

**Comment by feiyunzhang** [comment]
> hello, thanks for building this project! I want to finetune my own dataset using this method. Do you have the pretrained weights trained in Kinetics or other large-scale datasets？

Sorry,I do not have  the pretrained weights

**Comment by feiyunzhang** [comment]
http://pbzrvm8c9.bkt.clouddn.com/model/kinetics_i3dresnet101__rgb_model_best.pth.tar
