### ISSUE TITLE
请问i3d-non-local预训练模型在哪里可以找到

### ISSUE THREAD

**Issue by zhujiwei1234** [feiyunzhang/i3d-nonlocal-pytorch#11]
请问i3d-non-local预训练模型在哪里可以找到

**Comment by feiyunzhang** [comment]
> 请问i3d-non-local预训练模型在哪里可以找到

http://pbzrvm8c9.bkt.clouddn.com/model/kinetics_i3dresnet101__rgb_model_best.pth.tar

**Comment by zhujiwei1234** [comment]
谢谢！



















在 2020-04-21 10:18:29，"feiyunzhang" <notifications@github.com> 写道：

请问i3d-non-local预训练模型在哪里可以找到

http://pbzrvm8c9.bkt.clouddn.com/model/kinetics_i3dresnet101__rgb_model_best.pth.tar
