### ISSUE TITLE
have you trained the model with kinetics dataset?

### ISSUE THREAD

**Issue by yanxp** [feiyunzhang/i3d-nonlocal-pytorch#2]
Can you provide a pretrained kinetics model?

**Comment by feiyunzhang** [comment]
I just run 45 epoch about 62% MAP, it needs to train about 120 epoch to get to the paper's reuslt. Maybe it have some problems about nonlocal moudel. You can download the model here: http://pbzrvm8c9.bkt.clouddn.com/model/kinetics_i3dresnet101__rgb_model_best.pth.tar
