### ISSUE TITLE
Can you provide a new pretrained kinetics model?

### ISSUE THREAD

**Issue by crazycv** [feiyunzhang/i3d-nonlocal-pytorch#4]
I want to use the i3d-non-local network to finetune my own video dataset. The old model http://pbzrvm8c9.bkt.clouddn.com/model/kinetics_i3dresnet101__rgb_model_best.pth.tar can't work. so can you provided a new pretrained kinetics model?thank you~~

**Comment by feiyunzhang** [comment]
sorry, i did not train any other model...

**Comment by Caoliangjie** [comment]
Hello, I wonder if you have finished the function of end-to-end or not?

**Comment by feiyunzhang** [comment]
if i have time i will provide a new model and update the code
