### ISSUE TITLE
RuntimeError: CUDA error: initialization error

### ISSUE THREAD

**Issue by hulianyuyy** [feiyunzhang/i3d-nonlocal-pytorch#7]
When i tried to run this code on hmdb51 dataset for test,i got this error when an epoch run to its end point. Both python2 and python3 crashed too.
Traceback (most recent call last):
  File "main.py", line 278, in <module>
    main()
  File "main.py", line 106, in main
    train(train_loader, i3d_model, criterion, optimizer, epoch)
  File "main.py", line 134, in train
    for i, (input, target) in enumerate(train_loader):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/_utils/collate.py", line 68, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/_utils/collate.py", line 59, in default_collate
    return torch.tensor(batch)
RuntimeError: CUDA error: initialization error

**Comment by feiyunzhang** [comment]
> When i tried to run this code on hmdb51 dataset for test,i got this error when an epoch run to its end point. Both python2 and python3 crashed too.
> Traceback (most recent call last):
> File "main.py", line 278, in 
> main()
> File "main.py", line 106, in main
> train(train_loader, i3d_model, criterion, optimizer, epoch)
> File "main.py", line 134, in train
> for i, (input, target) in enumerate(train_loader):
> File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 582, in **next**
> return self._process_next_batch(batch)
> File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
> raise batch.exc_type(batch.exc_msg)
> RuntimeError: Traceback (most recent call last):
> File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
> samples = collate_fn([dataset[i] for i in batch_indices])
> File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/_utils/collate.py", line 68, in default_collate
> return [default_collate(samples) for samples in transposed]
> File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/_utils/collate.py", line 59, in default_collate
> return torch.tensor(batch)
> RuntimeError: CUDA error: initialization error

try to set   --workers = 0, and the pytorch==0.3.1

**Comment by hulianyuyy** [comment]
ok i will have a try . thanks

**Comment by hulianyuyy** [comment]
i tried to run it on Pytorch 0.3.1 but failed too. again i tried to run on another machine with Cuda 9.0 and succeeded.so the problem is due to the Cuda version and the Pytorch version correspondingly.
