### ISSUE TITLE
Inflated ImageNet Weights

### ISSUE THREAD

**Issue by ilkarman** [feiyunzhang/i3d-nonlocal-pytorch#9]
I was wondering if you saw any issue with me using the [inflat_weights function](https://github.com/feiyunzhang/i3d-non-local-pytorch/blob/master/models/i3dnon.py#L174) to use image-net (not kinetics) weights? 

```
def inflate_weights(model_2d, model_3d):
    pretrained_dict_2d = model_2d.state_dict()
    model_dict_3d = model_3d.state_dict()
    for key, weight_2d in pretrained_dict_2d.items():
        if key in model_dict_3d:
            if 'conv' in key:
                time_kernel_size = model_dict_3d[key].shape[2]
                if 'weight' in key:
                    weight_3d = weight_2d.unsqueeze(2).repeat(1, 1, time_kernel_size, 1, 1)
                    weight_3d = weight_3d / time_kernel_size
                    model_dict_3d[key] = weight_3d
                elif 'bias' in key:
                    model_dict_3d[key] = weight_2d
            elif 'bn' in key:
                model_dict_3d[key] = weight_2d
            #elif 'fc' in key:
            #    if 'weight' in key:
            #        time_kernel_size = model_dict_3d[key].shape[1] / weight_2d.shape[1]
            #        weight_3d = weight_2d.repeat(1, int(time_kernel_size))
            #        weight_3d = weight_3d / time_kernel_size
            #        model_dict_3d[key] = weight_3d
            #    elif 'bias' in key:
            #        model_dict_3d[key] = weight_2d
            elif 'downsample' in key:
                if '0.weight' in key:
                    time_kernel_size = model_dict_3d[key].shape[2]
                    weight_3d = weight_2d.unsqueeze(2).repeat(1, 1, time_kernel_size, 1, 1)
                    weight_3d = weight_3d / time_kernel_size
                    model_dict_3d[key] = weight_3d
                else :
                    model_dict_3d[key] = weight_2d
    model_3d.load_state_dict(model_dict_3d)
    return model_3d
```

Like so:

```
pretrained_model_2d = torchvision.models.resnet101(pretrained=True)
model = inflate_weights(pretrained_model_2d, model)
```

This doesn't produce an error but wanted to check if you foresaw any issues

**Comment by feiyunzhang** [comment]
You can use it this way

> I was wondering if you saw any issue with me using the [inflat_weights function](https://github.com/feiyunzhang/i3d-non-local-pytorch/blob/master/models/i3dnon.py#L174) to use image-net (not kinetics) weights?
> 
> ```
> def inflate_weights(model_2d, model_3d):
>     pretrained_dict_2d = model_2d.state_dict()
>     model_dict_3d = model_3d.state_dict()
>     for key, weight_2d in pretrained_dict_2d.items():
>         if key in model_dict_3d:
>             if 'conv' in key:
>                 time_kernel_size = model_dict_3d[key].shape[2]
>                 if 'weight' in key:
>                     weight_3d = weight_2d.unsqueeze(2).repeat(1, 1, time_kernel_size, 1, 1)
>                     weight_3d = weight_3d / time_kernel_size
>                     model_dict_3d[key] = weight_3d
>                 elif 'bias' in key:
>                     model_dict_3d[key] = weight_2d
>             elif 'bn' in key:
>                 model_dict_3d[key] = weight_2d
>             #elif 'fc' in key:
>             #    if 'weight' in key:
>             #        time_kernel_size = model_dict_3d[key].shape[1] / weight_2d.shape[1]
>             #        weight_3d = weight_2d.repeat(1, int(time_kernel_size))
>             #        weight_3d = weight_3d / time_kernel_size
>             #        model_dict_3d[key] = weight_3d
>             #    elif 'bias' in key:
>             #        model_dict_3d[key] = weight_2d
>             elif 'downsample' in key:
>                 if '0.weight' in key:
>                     time_kernel_size = model_dict_3d[key].shape[2]
>                     weight_3d = weight_2d.unsqueeze(2).repeat(1, 1, time_kernel_size, 1, 1)
>                     weight_3d = weight_3d / time_kernel_size
>                     model_dict_3d[key] = weight_3d
>                 else :
>                     model_dict_3d[key] = weight_2d
>     model_3d.load_state_dict(model_dict_3d)
>     return model_3d
> ```
> 
> Like so:
> 
> ```
> pretrained_model_2d = torchvision.models.resnet101(pretrained=True)
> model = inflate_weights(pretrained_model_2d, model)
> ```
> 
> This doesn't produce an error but wanted to check if you foresaw any issues

You can use it this way

**Comment by ilkarman** [comment]
Thank you!
